#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/Users/ijimin/jaman/02_dev/02_side_project/playground/node_modules/.pnpm/contentlayer@0.3.4_esbuild@0.18.20/node_modules/contentlayer/bin/node_modules:/Users/ijimin/jaman/02_dev/02_side_project/playground/node_modules/.pnpm/contentlayer@0.3.4_esbuild@0.18.20/node_modules/contentlayer/node_modules:/Users/ijimin/jaman/02_dev/02_side_project/playground/node_modules/.pnpm/contentlayer@0.3.4_esbuild@0.18.20/node_modules:/Users/ijimin/jaman/02_dev/02_side_project/playground/node_modules/.pnpm/node_modules"
else
  export NODE_PATH="/Users/ijimin/jaman/02_dev/02_side_project/playground/node_modules/.pnpm/contentlayer@0.3.4_esbuild@0.18.20/node_modules/contentlayer/bin/node_modules:/Users/ijimin/jaman/02_dev/02_side_project/playground/node_modules/.pnpm/contentlayer@0.3.4_esbuild@0.18.20/node_modules/contentlayer/node_modules:/Users/ijimin/jaman/02_dev/02_side_project/playground/node_modules/.pnpm/contentlayer@0.3.4_esbuild@0.18.20/node_modules:/Users/ijimin/jaman/02_dev/02_side_project/playground/node_modules/.pnpm/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../bin/cli.cjs" "$@"
else
  exec node  "$basedir/../../bin/cli.cjs" "$@"
fi
